// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'about_us.page.dart';

class Module with ThrioModule, ModuleParamScheme, ModulePageBuilder {
  @override
  String get key => 'about_us';

  @override
  void onPageBuilderSetting(final ModuleContext moduleContext) =>
      pageBuilder = (final settings) => AboutUsPage(
        moduleContext: moduleContext,
        settings: settings,
      );

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme('stringKeyBiz1');
  }
}


