import 'package:flutter/widgets.dart';

class CommonIcon {
    CommonIcon._();
    static const IconData icSettings =  IconData( 0xe613, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icRevoke =  IconData( 0xe652, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icTouchDot =  IconData( 0xe651, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icInteraction =  IconData( 0xe650, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icEyeVisible =  IconData( 0xe611, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icEyeInvisible =  IconData( 0xe612, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icMan =  IconData( 0xe64e, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icWoman =  IconData( 0xe64f, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icClose =  IconData( 0xe64c, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icDown =  IconData( 0xe64d, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icMore =  IconData( 0xe64a, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icArrowDown1 =  IconData( 0xe64b, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icArrowDown =  IconData( 0xe649, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icLink =  IconData( 0xe645, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icFile =  IconData( 0xe646, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icImage =  IconData( 0xe647, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icFolder =  IconData( 0xe648, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icPlusCircle =  IconData( 0xe643, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icSearch =  IconData( 0xe644, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icUndo =  IconData( 0xe641, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icShareInternal =  IconData( 0xe642, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icSchedule =  IconData( 0xe63e, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icMinusCircle =  IconData( 0xe63f, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icCloseCircle =  IconData( 0xe640, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icArchive =  IconData( 0xe639, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icNav =  IconData( 0xe63a, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icDelete1 =  IconData( 0xe63b, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icDoubleUp =  IconData( 0xe63c, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icSafe =  IconData( 0xe63d, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icCheckbox =  IconData( 0xe634, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icShake =  IconData( 0xe635, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icLock =  IconData( 0xe636, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icCloseCircleFill =  IconData( 0xe637, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icFilter =  IconData( 0xe633, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icStar =  IconData( 0xe62b, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icIm =  IconData( 0xe62c, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icSubscribed =  IconData( 0xe62d, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icMobile =  IconData( 0xe62e, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icMessage =  IconData( 0xe62f, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icUserGroup =  IconData( 0xe630, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icUser =  IconData( 0xe631, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icPhone =  IconData( 0xe632, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icArrowRight =  IconData( 0xe627, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icInteractive =  IconData( 0xe628, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icDelete =  IconData( 0xe629, fontFamily: 'BcIcon', fontPackage: 'common_lib');
    static const IconData icUnlock =  IconData( 0xe62a, fontFamily: 'BcIcon', fontPackage: 'common_lib');
}