name: flutter_module
description: flutter_demo_ios

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_thrio: ^4.6.1

  extended_text: ^11.1.0
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2

  todo_flutter:
    git:
      url: https://github.com/azhon/todo-flutter
      ref: 1.0.0

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_res:
  isModule: false
  prefix: yxd

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
