// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_jsonable/flutter_jsonable.dart';
import 'package:flutter_thrio/flutter_thrio.dart';

import 'about_us/module.dart' as about_us;
import 'types/user_profile.dart';

class Module
    with
        ThrioModule,
        ModuleJsonDeserializer,
        ModuleJsonSerializer,
        ModuleJsonable,
        ModuleParamScheme {
  @override
  String get key => 'user';

  @override
  void onModuleRegister(final ModuleContext moduleContext) {
    registerModule(about_us.Module(), moduleContext);
  }

  @override
  void onParamSchemeRegister(final ModuleContext moduleContext) {
    registerParamScheme('intKeyRootModule');
    registerParamScheme('people');
  }

  @override
  void onJsonableRegister(final ModuleContext moduleContext) {
    registerJsonable<UserProfile>(JsonableBuilder<UserProfile>(
          (final obj) => obj.toJson(),
      UserProfile.fromJson,
    ));
  }

  @override
  void onJsonSerializerRegister(final ModuleContext moduleContext) {
    registerJsonSerializer<UserProfile>((final i) => i<UserProfile>().toJson());
  }

  @override
  void onJsonDeserializerRegister(final ModuleContext moduleContext) {
    registerJsonDeserializer(UserProfile.fromJson);
  }
}
