// Copyright (c) 2023 foxsofter.
//
// Do not edit this file.
//

import 'package:flutter_thrio/flutter_thrio.dart';

import 'about_us/about_us.route.dart';

final user = AppRoute();

class AppRoute extends NavigatorRouteNode {
  factory AppRoute() => _instance ??= AppRoute._();

  AppRoute._() : super.home();

  static AppRoute? _instance;

  late final about_us = AboutUsRoute(this);

  @override
  String get name => 'user';

  /// 当登录成功后调用
  ///
  /// `userName` user name of login user.
  ///
  Future<bool> login({
    final int? uid,
    required final String userName,
    final String userToken = 'good token',
  }) =>
      ThrioNavigator.notify(
        url: url,
        name: 'login',
        params: {
          'uid': uid,
          'userName': userName,
          'userToken': userToken,
        },
      );

  Future<bool> logout() => ThrioNavigator.notify(
    url: url,
    name: 'logout',
  );
}
